name: featured-intersection-van

on:
  schedule:
    # run at 18:08 PST on Mondays, Wednesdays  (GitHub actions in UTC)
    #- cron: '8 2 * * 2,4'
    - cron: '0 * * * *'

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Post tweet
        run: python3 post_tweet.py "Vancouver"
